FROM golang:1.20 AS build-stage

WORKDIR /app

COPY ./go.mod ./go.sum ./main.go ./
COPY ./internal ./internal

RUN go mod download

RUN GOOS=linux go build -o /knt .

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage

WORKDIR /

COPY --from=build-stage /knt /knt
COPY ./config ./config

EXPOSE 5000

ENTRYPOINT ["/knt"]
