# Generated by Django 4.2.1 on 2023-05-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("data", models.TextField()),
                ("timestamp", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TaxCategory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("percentage", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("vunetid", models.CharField(max_length=120, unique=True)),
                ("password", models.IntegerField()),
                ("balance", models.IntegerField(default=0)),
                ("visibility", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("starting_balance", models.IntegerField()),
                ("delta_balance", models.IntegerField()),
                ("final_balance", models.IntegerField()),
                ("ref", models.TextField()),
                (
                    "receipt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="knt_backend.receipt",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="knt_backend.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("price", models.IntegerField()),
                ("name", models.TextField()),
                ("visibility", models.IntegerField(default=1)),
                (
                    "taxcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="knt_backend.taxcategory",
                    ),
                ),
            ],
        ),
    ]
