# Generated by Django 4.2.1 on 2023-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knt_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
