# Generated by Django 4.2.1 on 2023-05-12 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knt_backend", "0004_alter_user_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                ("tax", models.IntegerField()),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="knt_backend.product",
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="knt_backend.transaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction_id", "product_id")},
            },
        ),
    ]
