# Generated by Django 4.2.1 on 2023-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knt_backend", "0006_alter_product_id_alter_receipt_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="receipt_id",
            new_name="receipt",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="transactionitem",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="transactionitem",
            old_name="transaction_id",
            new_name="transaction",
        ),
    ]
